routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
    //return view('welcome');
});

Auth::routes();

Route::get('/home', 'FirstController@index')->name('home');

Route::get('/project/createcustomer/{id}', 'ProjectController@createCustomer')->name('project.createCustomer');
Route::post('/project/createcustomer', 'ProjectController@storeCustomer')->name('project.storeCustomer');
Route::get('/project/selectcustomer/{id}', 'ProjectController@selectCustomer')->name('project.selectCustomer');
Route::post('/project/selectcustomer', 'ProjectController@storeSelectedCustomer')->name('project.storeSelectedCustomer');

Route::get('/order/selectexample/{id}', 'OrderController@selectExample')->name('order.selectExample');
Route::post('/order/selectexample', 'OrderController@storeSelectedExample')->name('order.storeSelectedExample');



Route::get('/order/selectnature/{order_id}', 'OrderController@selectNature')->name('order.selectNature');
Route::post('/order/createmodule', 'OrderController@passCreateModule')->name('order.passCreateModule');
Route::get('/order/createmodule/{order_id}/{nature_id}', 'OrderController@createModule')->name('order.createModule');
Route::post('/order/storecreatedmodule', 'OrderController@storeCreatedModule')->name('order.storeCreatedModule');
Route::get('/order/editmodule/{id}', 'OrderController@editModule')->name('order.editModule');
Route::post('/order/updateEditedModule', 'OrderController@updateEditedModule')->name('order.updateEditedModule');
Route::get('/order/confirmdeletemodule/{id}', 'OrderController@confirmDeleteModule')->name('order.confirmDeleteModule');
Route::get('/order/deletemodule/{id}', 'OrderController@deleteModule')->name('order.deleteModule');


Route::get('/estimate/validateestimate/{id}', 'EstimateController@validateEstimate')->name('estimate.validateEstimate');
Route::post('/estimate/validateestimate', 'EstimateController@storeEstimate')->name('estimate.storeEstimate');

Route::resource('order', 'OrderController');
Route::resource('estimate', 'EstimateController');
Route::resource('project', 'ProjectController');
Route::resource('customer', 'CustomerController');
Route::resource('row', 'RowController');
Route::resource('module', 'ModuleController');
Route::resource('range', 'RangeController');
Route::resource('example', 'ExampleController');
Route::resource('moduleexample', 'ModuleExampleController');
Route::resource('angle', 'AngleController');
Route::resource('insulation', 'InsulationController');
Route::resource('finish', 'FinishController');
Route::resource('cover', 'CoverController');
Route::resource('frame', 'FrameController');
Route::resource('nature', 'NatureController');
Route::resource('moduleorder', 'ModuleOrderController');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model {

	protected $table = 'projects';
	public $timestamps = true;
	protected $fillable = array('name', 'reference', 'customer_id');

	public function orders()
	{
		return $this->hasMany('App\Order');
	}

	public function customer()
	{
		return $this->belongsTo('App\Customer');
	}

}

app/Http/Controllers/ProjectController.php
<?php 

namespace App\Http\Controllers;
use App\Estimate;
use App\Project;
use App\Customer;
use App\Order;
use Illuminate\Http\Request;

class ProjectController extends Controller {

    public function __construct()
    {
        $this->middleware('auth');
    }

  /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
    $projects = Project::orderBy('created_at','desc')->get();
    return view('project.index', ['projects' => $projects]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Response
   */
  public function create()
  {
      $projectCount = Project::all()->count();
      $projectCount = $projectCount + 1;
    return view('project.create', ['count' => $projectCount]);
  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store(Request $request)
  {
      $this->validate($request, [
          'name' => 'required|max:255',
          'reference' => 'max:255',
      ]);

      $project = new Project();
      $project->name = $request->name;
      $project->reference = $request->reference;
      $project->save();

      return redirect()->route('project.show', ['id' => $project->id]);
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
    $project = Project::with('customer')->findOrFail($id);
    $orders = Order::where('project_id',$id)->get();
    $estimates = Estimate::where('project_id',$id)->get();
    return view('project.show', ["project" => $project, 'orders' => $orders, 'estimates' => $estimates]);
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
    $project = Project::findOrFail($id);
    return view('project.edit', ['project' => $project]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function update($id, Request $request)
  {
      $this->validate($request, [
          'name' => 'required|max:255',
          'reference' => 'max:255',
      ]);

    $project = Project::findOrFail($id);
    $project->name = $request->name;
    $project->reference = $request->reference;
    $project->save();

    return redirect()->route('project.show', $project->id);
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
    
  }

  public function createCustomer($id)
  {
      return view('project.createCustomer', ['project_id' => $id]);
  }

  public function storeCustomer(Request $request)
  {
      $this->validate($request, [
          'name' => 'required|max:255',
          'firstname' => 'required|max:255',
          'phone' => 'required|max:255',
          'mail' => 'required|max:255',
          'address' => 'required|max:255',
          'postalCode' => 'required|max:5',
          'city' => 'required|max:255',
      ]);

      $project = Project::findOrFail($request->project_id);

      $customer = new Customer();
      $customer->name = $request->name;
      $customer->firstname = $request->firstname;
      $customer->phone = $request->phone;
      $customer->mail = $request->mail;
      $customer->address = $request->address;
      $customer->postalCode = $request->postalCode;
      $customer->city = $request->city;

      $customer->save();
      $project->customer_id = $customer->id;
      $project->save();

      return redirect()->route('project.show',$project->id);
  }

  public function selectCustomer($id)
  {
      $customers = Customer::all();
      return view('project.selectCustomer', ['project_id' => $id, 'customers' => $customers]);
  }

  public function storeSelectedCustomer(Request $request)
  {
      $this->validate($request, [
          'customer_id' => 'required|integer',
      ]);

      $project = Project::findOrFail($request->project_id);
      $project->customer_id = $request->customer_id;
      $project->save();

      return redirect()->route('project.show', $project->id);
  }

}

?>

resources/views/project/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <a href="{{route('home')}}">Accueil</a>
                    /
                    Nouveau projet
                </p>

                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <div class="panel panel-default">
                    <div class="panel-heading">Formulaire de création d'un projet</div>

                    <div class="panel-body">

                        <form action="{{route('project.store')}}" method="POST">
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="">Nom du projet</label>
                                <input type="text" name="name" class="form-control" @if(!old('name'))value="Projet n° {{$count}}" @else value="{{old('name')}}" @endif required>
                            </div>
                            <div class="form-group">
                                <label for="">Référence projet</label>
                                <input type="text" name="reference" class="form-control" value="{{ old('reference') }}">
                            </div>

                            <div class="col-md-12 text-center">
                                <a href="{{route('home')}}" class="btn btn-lg btn-default"> <i class=" fa fa-undo" aria-hidden="true"></i> Annuler</a>
                                <button type="submit" class="btn btn-lg btn-success">Créer le projet</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/project/createCustomer.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <a href="{{route('home')}}">Accueil</a>
                    /
                    <a href="{{route('project.show',$project_id)}}">Projet</a>
                    /
                    Création d'un client
                </p>

                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif


                <div class="panel panel-default">
                    <div class="panel-heading">Créer un client pour le projet</div>

                    <div class="panel-body">
                        <form action="{{route('project.storeCustomer')}}" method="POST">
                            {{ csrf_field() }}


                                <input type="text" name="project_id" value="{{$project_id}}" required hidden>

                            <div class="form-group">
                                <label for="">Nom du client</label>
                                <input type="text" name="name" class="form-control" required value="{{ old('name') }}">
                            </div>

                            <div class="form-group">
                                <label for="">Prenom du client</label>
                                <input type="text" name="firstname" class="form-control" required value="{{ old('firstname') }}">
                            </div>

                            <div class="form-group">
                                <label for="">Téléphone</label>
                                <input type="text" name="phone" class="form-control" required value="{{ old('phone') }}">
                            </div>

                            <div class="form-group">
                                <label for="">Adresse mail</label>
                                <input type="email" name="mail" class="form-control" required value="{{ old('mail') }}">
                            </div>

                            <div class="form-group">
                                <label for="">Adresse du client</label>
                                <input type="text" name="address" class="form-control" required value="{{ old('address') }}">
                            </div>

                            <div class="form-group">
                                <label for="">Code postal</label>
                                <input type="text" name="postalCode" class="form-control" required value="{{ old('postalCode') }}">
                            </div>

                            <div class="form-group">
                                <label for="">Ville</label>
                                <input type="text" name="city" class="form-control" required value="{{ old('city') }}">
                            </div>

                            <div class="col-md-12 text-center">
                                <a href="{{route('project.show', $project_id)}}" class="btn btn-lg btn-default"> <i class=" fa fa-undo" aria-hidden="true"></i> Annuler</a>
                                <button type="submit" class="btn btn-lg btn-success">Créer le client</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/project/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <a href="{{route('home')}}">Accueil</a>
                    /
                    Mise à jour du projet
                </p>

                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <div class="panel panel-default">
                    <div class="panel-heading">Formulaire de modification d'un projet</div>

                    <div class="panel-body">

                        <form action="{{route('project.update', $project->id)}}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}

                            <div class="form-group">
                                <label for="">Nom du projet</label>
                                <input type="text" name="name" class="form-control" @if(!old('name')) value="{{$project->name}}" @else value="{{ old('name') }}" @endif required>
                            </div>
                            <div class="form-group">
                                <label for="">Référence projet</label>
                                <input type="text" name="reference" class="form-control" @if(!old('reference')) value="{{$project->reference}}" @else value="{{old('reference')}}" @endif>
                            </div>

                            <div class="col-md-12 text-center">
                                <a href="{{route('project.show', $project->id)}}" class="btn btn-lg btn-default"><i class="fa fa-undo" aria-hidden="true"></i> Annuler</a>
                                <button type="submit" class="btn btn-success btn-lg"> <i class="fa fa-floppy-o" aria-hidden="true"></i> Modifier les informations du projet</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/project/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <a href="{{route('home')}}">Accueil</a>
                    /
                    Projets
                </p>
                <div class="panel panel-default">

                    <div class="panel-heading">Liste des derniers projets</div>

                    <div class="panel-body">
                        <div class="col-md-12 ">
                            <p><a class="btn btn-default " href="{{route('project.create')}}"><i class="fa fa-home" aria-hidden="true"></i> Créer un nouveau projet</a></p>
                        </div>

                        @if($projects->count())
                            <table class="table-bordered table">
                                <tr>
                                    <th>Nom du projet</th>
                                    <th>Référence</th>
                                    <th>Client</th>
                                    <th>Date</th>
                                    <th></th>
                                </tr>
                                @foreach($projects as $project)
                                    <tr>
                                        <td><a href="{{route('project.show',$project->id)}}">{{$project->name}}</a></td>
                                        <td>{{$project->reference}}</td>
                                        <td>@if($project->customer_id != null)
                                                {{$project->customer->name}} {{$project->customer->firstname}}
                                            @else
                                                Pas de client
                                            @endif </td>
                                        <td>{{date('d / m / Y', strtotime($project->created_at))}}</td>
                                        <td><a href="{{route('project.show', $project->id)}}" class="btn btn-default"><i class="fa fa-file" aria-hidden="true"></i> Voir le projet</a></td>

                                    </tr>
                                @endforeach
                            </table>
                            @else
                        <p><strong>Aucun projet dans la base de données</strong></p>
                            @endif

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/project/selectCustomer.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <a href="{{route('home')}}">Accueil</a>
                    /
                    <a href="{{route('project.show',$project_id)}}">Projet</a>
                    /
                    Sélection d'un client
                </p>

                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <div class="panel panel-default">
                    <div class="panel-heading">Choisir un client pour le projet</div>

                    <div class="panel-body">

                        @if($customers->count())
                            <table class="table table-bordered">
                                <tr>
                                    <th>Nom</th>
                                    <th>Prenom</th>
                                    <th>Ville</th>
                                    <th>Selection</th>
                                </tr>
                                @foreach($customers as $customer)
                                    <tr>
                                        <td>{{$customer->name}}</td>
                                        <td>{{$customer->firstname}}</td>
                                        <td>{{$customer->city}}</td>
                                        <td>
                                            <form action="{{route('project.storeSelectedCustomer')}}" method="post">
                                                {{ csrf_field() }}
                                                <input value="{{$customer->id}}" name="customer_id" type="text" hidden required>
                                                <input value="{{$project_id}}" name="project_id" type="text" hidden required>
                                                <button type="submit" class="btn btn-default"><i class="fa fa-user" aria-hidden="true"></i> Choisir ce client</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </table>
                            @else
                            <p><strong>Aucun client dans la base de données</strong></p>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/project/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <a href="{{route('home')}}">Accueil</a>
                    /
                    Projet
                </p>
                <div class="panel panel-default">
                    <div class="panel-heading">{{$project->name}}</div>

                    <div class="panel-body">
                        <h2>Information sur le projet {{$project->name}}</h2>
                        <p>Numéro : <strong>{{$project->id}}</strong> </p>
                        <p>Nom : <strong>{{$project->name}}</strong></p>
                        <p>Référence : <strong>{{$project->reference}}</strong></p>

                        <p><a href="{{route('project.edit', $project->id)}}" class="btn btn-default"><i class="fa fa-pencil" aria-hidden="true"></i> Modifier les informations</a></p>



                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">Client</div>

                    <div class="panel-body">
                        @if($project->customer_id)
                            <p><strong>{{$project->customer->name}} {{$project->customer->firstname}}</strong></p>
                            <label>Téléphone</label>
                            <p>{{$project->customer->phone}}</p>
                            <label>E-Mail</label>
                            <p>{{$project->customer->mail}}</p>
                            <label>Adresse</label>
                            <p>{{$project->customer->address}} <br> {{$project->customer->postalCode}} {{$project->customer->city}}</p>
                            <p><a href="{{route('customer.show', $project->customer->id)}}" class="btn btn-default"><i class="fa fa-user" aria-hidden="true"></i> Voir le client</a></p>
                        @else
                            Associer un client : <br>
                            <a href="{{route('project.createCustomer', $project->id)}}" class="btn btn-default"><i class="fa fa-user-o" aria-hidden="true"></i> Créer un client pour ce projet</a><br>
                            <br>
                            <a href="{{route('project.selectCustomer', $project->id)}}" class="btn btn-default"><i class="fa fa-user" aria-hidden="true"></i> Ajouter un client existant</a><br><br>
                        @endif
                </div>


                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">Commandes en cours</div>

                    <div class="panel-body">

                        <a href="{{route('order.selectExample', $project->id)}}" class="btn btn-default"><i class="fa fa-file" aria-hidden="true"></i> Créer une commande</a><br><br>

                        @if($orders->count())
                            <table class="table table-bordered">
                                <tr>
                                    <th>Numéro</th>
                                    <th>Nb modules</th>
                                    <th>Estimation</th>

                                    <th>Date</th>

                                    <th></th>
                                </tr>
                                @foreach($orders as $order)

                                        <tr>
                                            <td><a href="{{route('order.show', $order->id)}}">
                                                    Numéro {{$order->id}}
                                                </a></td>

                                            <td>{{$order->modules->count()}}</td>
                                            <td>{{$order->getTotalPrice()}} €</td>
                                            <td>{{date('d / m / Y', strtotime($order->created_at))}}</td>

                                            <td><a href="{{route('order.show', $order->id)}}" class="btn btn-default">
                                                    <i class="fa fa-file" aria-hidden="true"></i> Voir la commande
                                                </a></td>
                                        </tr>

                                @endforeach
                            </table>
                        @else
                            Aucune commande.
                        @endif
                    </div>


                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">Devis de ce projet</div>

                    <div class="panel-body">

                        @if($estimates->count())
                            <table class="table table-bordered">
                                <tr>
                                    <th>Numéro devis</th>
                                    <th>Nombre de modules</th>
                                    <th>Prix total</th>
                                    <th>Date</th>
                                    <th>Nb jour validité</th>
                                    <th></th>
                                </tr>
                                @foreach($estimates as $estimate)
                                    <tr>
                                        <td><a href="{{route('estimate.show', $estimate->id)}}">Devis n° {{$estimate->id}}</a></td>
                                        <td>{{$estimate->rows->count()}}</td>
                                        <td>{{$estimate->price}} €</td>
                                        <td>{{$estimate->created_at}}</td>
                                        <td>{{$estimate->days}}</td>
                                        <td><a href="{{route('estimate.show', $estimate->id)}}" class="btn btn-default"><i class="fa fa-file" aria-hidden="true"></i> Voir le devis</a></td>
                                    </tr>
                                @endforeach
                            </table>
                            @else
                        Aucun devis pour ce projet
                            @endif

                    </div>


                </div>



            </div>
        </div>
    </div>
@endsection