routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
    //return view('welcome');
});

Auth::routes();

Route::get('/home', 'FirstController@index')->name('home');

Route::get('/project/createcustomer/{id}', 'ProjectController@createCustomer')->name('project.createCustomer');
Route::post('/project/createcustomer', 'ProjectController@storeCustomer')->name('project.storeCustomer');
Route::get('/project/selectcustomer/{id}', 'ProjectController@selectCustomer')->name('project.selectCustomer');
Route::post('/project/selectcustomer', 'ProjectController@storeSelectedCustomer')->name('project.storeSelectedCustomer');

Route::get('/order/selectexample/{id}', 'OrderController@selectExample')->name('order.selectExample');
Route::post('/order/selectexample', 'OrderController@storeSelectedExample')->name('order.storeSelectedExample');



Route::get('/order/selectnature/{order_id}', 'OrderController@selectNature')->name('order.selectNature');
Route::post('/order/createmodule', 'OrderController@passCreateModule')->name('order.passCreateModule');
Route::get('/order/createmodule/{order_id}/{nature_id}', 'OrderController@createModule')->name('order.createModule');
Route::post('/order/storecreatedmodule', 'OrderController@storeCreatedModule')->name('order.storeCreatedModule');
Route::get('/order/editmodule/{id}', 'OrderController@editModule')->name('order.editModule');
Route::post('/order/updateEditedModule', 'OrderController@updateEditedModule')->name('order.updateEditedModule');
Route::get('/order/confirmdeletemodule/{id}', 'OrderController@confirmDeleteModule')->name('order.confirmDeleteModule');
Route::get('/order/deletemodule/{id}', 'OrderController@deleteModule')->name('order.deleteModule');


Route::get('/estimate/validateestimate/{id}', 'EstimateController@validateEstimate')->name('estimate.validateEstimate');
Route::post('/estimate/validateestimate', 'EstimateController@storeEstimate')->name('estimate.storeEstimate');

Route::resource('order', 'OrderController');
Route::resource('estimate', 'EstimateController');
Route::resource('project', 'ProjectController');
Route::resource('customer', 'CustomerController');
Route::resource('row', 'RowController');
Route::resource('module', 'ModuleController');
Route::resource('range', 'RangeController');
Route::resource('example', 'ExampleController');
Route::resource('moduleexample', 'ModuleExampleController');
Route::resource('angle', 'AngleController');
Route::resource('insulation', 'InsulationController');
Route::resource('finish', 'FinishController');
Route::resource('cover', 'CoverController');
Route::resource('frame', 'FrameController');
Route::resource('nature', 'NatureController');
Route::resource('moduleorder', 'ModuleOrderController');

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model {

	protected $table = 'customers';
	public $timestamps = true;
	protected $fillable = array('name', 'firstname', 'phone', 'mail', 'address', 'postalCode', 'city');

	public function projects()
	{
		return $this->hasMany('App\Project');
	}

}

app/Http/Controllers/CustomerController.php
<?php 

namespace App\Http\Controllers;

use App\Customer;
use App\Estimate;
use Illuminate\Http\Request;

class CustomerController extends Controller {

    public function __construct()
    {
        $this->middleware('auth');
    }

  /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
    $customers = Customer::all();
    return view('customer.index', ['customers' => $customers]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Response
   */
  public function create()
  {
    return view('customer.create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store(Request $request)
  {
      $this->validate($request, [
          'name' => 'required|max:255',
          'firstname' => 'required|max:255',
          'phone' => 'required|max:255',
          'mail' => 'required|max:255',
          'address' => 'required|max:255',
          'postalCode' => 'required|max:5',
          'city' => 'required|max:255',
      ]);

      $customer = new Customer();
      $customer->name = $request->name;
      $customer->firstname = $request->firstname;
      $customer->phone = $request->phone;
      $customer->mail = $request->mail;
      $customer->address = $request->address;
      $customer->postalCode = $request->postalCode;
      $customer->city = $request->city;

      $customer->save();

      return redirect()->route('customer.show', $customer->id);
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
      $customer = Customer::findOrFail($id);
      $estimates = Estimate::where('customer_id', $id)->get();

      return view('customer.show', ['customer' => $customer, 'estimates' => $estimates]);
    
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
    $customer = Customer::findOrFail($id);
    return view('customer.edit', ['customer' => $customer]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function update(Request $request, $id)
  {
      $this->validate($request, [
          'name' => 'required|max:255',
          'firstname' => 'required|max:255',
          'phone' => 'required|max:255',
          'mail' => 'required|max:255',
          'address' => 'required|max:255',
          'postalCode' => 'required|max:5',
          'city' => 'required|max:255',
      ]);

      $customer = Customer::findOrFail($id);

      $customer->name = $request->name;
      $customer->firstname = $request->firstname;
      $customer->phone = $request->phone;
      $customer->mail = $request->mail;
      $customer->address = $request->address;
      $customer->postalCode = $request->postalCode;
      $customer->city = $request->city;

      $customer->save();

      return redirect()->route('customer.show', $customer->id);

  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
    
  }
  
}

?>

resources/views/customer/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <a href="{{route('home')}}">Accueil</a>
                    /
                    <a href="{{route('customer.index')}}">Clients</a>
                    /
                    Création d'un client
                </p>

                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif


                <div class="panel panel-default">
                    <div class="panel-heading">Créer un client</div>

                    <div class="panel-body">
                        <form action="{{route('customer.store')}}" method="POST">
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="">Nom du client</label>
                                <input type="text" name="name" class="form-control" required value="{{old('name')}}">
                            </div>

                            <div class="form-group">
                                <label for="">Prenom du client</label>
                                <input type="text" name="firstname" class="form-control" required value="{{old('firstname')}}">
                            </div>

                            <div class="form-group">
                                <label for="">Téléphone</label>
                                <input type="text" name="phone" class="form-control" required value="{{old('phone')}}">
                            </div>

                            <div class="form-group">
                                <label for="">Adresse mail</label>
                                <input type="mail" name="mail" class="form-control" required value="{{old('mail')}}">
                            </div>

                            <div class="form-group">
                                <label for="">Adresse du client</label>
                                <input type="text" name="address" class="form-control" required value="{{old('address')}}">
                            </div>

                            <div class="form-group">
                                <label for="">Code postal</label>
                                <input type="text" name="postalCode" class="form-control" required value="{{old('postalCode')}}">
                            </div>

                            <div class="form-group">
                                <label for="">Ville</label>
                                <input type="text" name="city" class="form-control" required value="{{old('city')}}">
                            </div>

                            <button type="submit" class="btn btn-default">Créer le client</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/customer/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <a href="{{route('home')}}">Accueil</a>
                    /
                    <a href="{{route('customer.index')}}">Clients</a>
                    /
                    Modification d'un client
                </p>

                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif


                <div class="panel panel-default">
                    <div class="panel-heading">Modifier un client</div>

                    <div class="panel-body">
                        <form action="{{route('customer.update', $customer->id)}}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field('put') }}

                            <div class="form-group">
                                <label for="">Nom du client</label>
                                <input type="text" name="name" class="form-control" required @if(!old('name')) value="{{$customer->name}}" @else value="{{old('name')}}" @endif>
                            </div>

                            <div class="form-group">
                                <label for="">Prenom du client</label>
                                <input type="text" name="firstname" class="form-control" required @if(!old('firstname')) value="{{$customer->firstname}}" @else value="{{old('firstname')}}" @endif>
                            </div>

                            <div class="form-group">
                                <label for="">Téléphone</label>
                                <input type="text" name="phone" class="form-control" required @if(!old('phone')) value="{{$customer->phone}}" @else value="{{old('phone')}}" @endif>
                            </div>

                            <div class="form-group">
                                <label for="">Adresse mail</label>
                                <input type="mail" name="mail" class="form-control" required @if(!old('mail')) value="{{$customer->mail}}" @else value="{{old('mail')}}" @endif>
                            </div>

                            <div class="form-group">
                                <label for="">Adresse du client</label>
                                <input type="text" name="address" class="form-control" required @if(!old('address')) value="{{$customer->address}}" @else value="{{old('address')}}" @endif>
                            </div>

                            <div class="form-group">
                                <label for="">Code postal</label>
                                <input type="text" name="postalCode" class="form-control" required @if(!old('postalCode')) value="{{$customer->postalCode}}" @else value="{{old('postalCode')}}" @endif>
                            </div>

                            <div class="form-group">
                                <label for="">Ville</label>
                                <input type="text" name="city" class="form-control" required @if(!old('city')) value="{{$customer->city}}" @else value="{{old('city')}}" @endif>
                            </div>

                            <div class="col-md-12 text-center">
                                <a href="{{route('customer.show', $customer->id)}}" class="btn btn-lg btn-default"><i class="fa fa-undo" aria-hidden="true"></i> Annuler</a>
                                <button type="submit" class="btn btn-lg btn-success"><i class="fa fa-floppy-o" aria-hidden="true"></i> Enregistrer les modifications</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/customer/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <a href="{{route('home')}}">Accueil</a>
                    /
                    Clients
                </p>
                <div class="panel panel-default">
                    <div class="panel-heading">Liste des clients</div>

                    <div class="panel-body">

                        <div class="col-md-12">
                            <p><a href="{{route('customer.create')}}" class="btn-default btn"><i class="fa fa-user" aria-hidden="true"></i> Créer un client</a></p>
                        </div>

                        @if($customers->count())
                            <table class="table table-bordered">
                                <tr>
                                    <th>Nom du client</th>
                                    <th>Ville</th>
                                    <th>Nb projet</th>
                                    <th></th>
                                </tr>

                                @foreach($customers as $customer)
                                    <tr>
                                        <td>{{$customer->name}} {{$customer->firstname}}</td>
                                        <td>{{$customer->city}}</td>
                                        <td>{{$customer->projects->count()}}</td>
                                        <td><a href="{{route('customer.show', $customer->id)}}" class="btn btn-default">Voir le client</a></td>

                                    </tr>
                                @endforeach
                            </table>
                        @else
                            <strong>Aucun client dans la base de données</strong>
                        @endif

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/customer/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <a href="{{route('home')}}">Accueil</a>
                    /
                    <a href="{{route('customer.index')}}">Clients</a>
                    /
                    Client {{$customer->id}}
                </p>
                <div class="panel panel-default">
                    <div class="panel-heading">{{$customer->name}} {{$customer->firstname}}</div>

                    <div class="panel-body">

                        <label>Téléphone</label>
                        <p>{{$customer->phone}}</p>
                        <label>E-Mail</label>
                        <p>{{$customer->mail}}</p>
                        <label>Adresse</label>
                        <p>{{$customer->address}} <br> {{$customer->postalCode}} {{$customer->city}}</p>

                        <p><a href="{{route('customer.edit', $customer->id)}}" class="btn btn-default"><i class="fa fa-pencil" aria-hidden="true"></i> Modifier le client</a></p>


                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">Projets du client</div>

                    <div class="panel-body">



                        @if($customer->projects->count())
                            <table class="table table-bordered">
                                <tr>
                                    <th>Nom du projet</th>
                                    <th>Reférence du projet</th>
                                    <th>Date</th>
                                    <th></th>
                                </tr>

                                @foreach($customer->projects as $project)
                                    <tr>
                                        <td><a href="{{route('project.show', $project->id)}}">{{$project->name}}</a></td>
                                        <td>{{$project->reference}}</td>
                                        <td>{{date('d / m / Y', strtotime($project->created_at))}}</td>
                                        <td><a href="{{route('project.show', $project->id)}}" class="btn btn-default"><i class="fa fa-file" aria-hidden="true"></i> Voir le projet</a></td>

                                    </tr>
                                @endforeach
                            </table>
                        @else
                            <strong>Le client n'a pas de projet</strong>
                        @endif

                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">Devis du client</div>

                    <div class="panel-body">



                        @if($estimates->count())
                            <table class="table table-bordered">
                                <tr>
                                    <th>Numéro devis</th>
                                    <th>Nombre de modules</th>
                                    <th>Prix total</th>
                                    <th>Date</th>
                                    <th>Nb jour validité</th>
                                    <th></th>
                                </tr>

                                @foreach($estimates as $estimate)
                                    <tr>
                                        <td><a href="{{route('estimate.show', $estimate->id)}}">Devis n° {{$estimate->id}}</a></td>
                                        <td>{{$estimate->rows->count()}}</td>
                                        <td>{{$estimate->price}} €</td>
                                        <td>{{date('d / m / Y', strtotime($estimate->created_at))}}</td>
                                        <td>{{$estimate->days}}</td>
                                        <td><a href="{{route('estimate.show', $estimate->id)}}" class="btn btn-default"><i class="fa fa-file" aria-hidden="true"></i> Voir le devis</a></td>
                                    </tr>
                                @endforeach
                            </table>
                        @else
                            <strong>Le client n'a pas de devis</strong>
                        @endif

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection