routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
    //return view('welcome');
});

Auth::routes();

Route::get('/home', 'FirstController@index')->name('home');

Route::get('/project/createcustomer/{id}', 'ProjectController@createCustomer')->name('project.createCustomer');
Route::post('/project/createcustomer', 'ProjectController@storeCustomer')->name('project.storeCustomer');
Route::get('/project/selectcustomer/{id}', 'ProjectController@selectCustomer')->name('project.selectCustomer');
Route::post('/project/selectcustomer', 'ProjectController@storeSelectedCustomer')->name('project.storeSelectedCustomer');

Route::get('/order/selectexample/{id}', 'OrderController@selectExample')->name('order.selectExample');
Route::post('/order/selectexample', 'OrderController@storeSelectedExample')->name('order.storeSelectedExample');



Route::get('/order/selectnature/{order_id}', 'OrderController@selectNature')->name('order.selectNature');
Route::post('/order/createmodule', 'OrderController@passCreateModule')->name('order.passCreateModule');
Route::get('/order/createmodule/{order_id}/{nature_id}', 'OrderController@createModule')->name('order.createModule');
Route::post('/order/storecreatedmodule', 'OrderController@storeCreatedModule')->name('order.storeCreatedModule');
Route::get('/order/editmodule/{id}', 'OrderController@editModule')->name('order.editModule');
Route::post('/order/updateEditedModule', 'OrderController@updateEditedModule')->name('order.updateEditedModule');
Route::get('/order/confirmdeletemodule/{id}', 'OrderController@confirmDeleteModule')->name('order.confirmDeleteModule');
Route::get('/order/deletemodule/{id}', 'OrderController@deleteModule')->name('order.deleteModule');


Route::get('/estimate/validateestimate/{id}', 'EstimateController@validateEstimate')->name('estimate.validateEstimate');
Route::post('/estimate/validateestimate', 'EstimateController@storeEstimate')->name('estimate.storeEstimate');

Route::resource('order', 'OrderController');
Route::resource('estimate', 'EstimateController');
Route::resource('project', 'ProjectController');
Route::resource('customer', 'CustomerController');
Route::resource('row', 'RowController');
Route::resource('module', 'ModuleController');
Route::resource('range', 'RangeController');
Route::resource('example', 'ExampleController');
Route::resource('moduleexample', 'ModuleExampleController');
Route::resource('angle', 'AngleController');
Route::resource('insulation', 'InsulationController');
Route::resource('finish', 'FinishController');
Route::resource('cover', 'CoverController');
Route::resource('frame', 'FrameController');
Route::resource('nature', 'NatureController');
Route::resource('moduleorder', 'ModuleOrderController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">
    <link href="/css/font-awesome.min.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ route('home') }}">
                        <img src="/img/logo.png" alt="Logo Madera" style="float: left;max-width: 30px"> {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        <li><a href="{{route('project.index')}}">Projets</a></li>
                        <li><a href="{{route('customer.index')}}">Clients</a></li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Connexion</a></li>
                            <!--<li><a href="{{ url('/register') }}">Register</a></li>-->
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Déconnexion
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="/js/app.js"></script>
</body>
</html>